import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {ANCHORS,DETAILED_ANCHOR_GROUPS,bounds,createRegion,changeRegion,splitRegion,validateInterval,validateReference,selectionRange,regionRows,isolateSelection,regionFromSelection} from '../assets/processing-timeline-edit.mjs';
import {timelineView,zoomView,panView,rulerTicks} from '../assets/viewport.mjs';
const backendAnchors=JSON.parse(execFileSync('python',['-c','import json,runpy; print(json.dumps(list(runpy.run_path("sam3d_funscript/anchors.py")["ANCHORS"])))'],{encoding:'utf8'}));
const pickerAnchors=[...ANCHORS,...Object.values(DETAILED_ANCHOR_GROUPS).flat()];
assert.equal(new Set(pickerAnchors).size,pickerAnchors.length,'general and detailed lists do not duplicate choices');
assert.deepEqual([...pickerAnchors].sort(),backendAnchors.sort(),'the browser exposes every supported anchor');
const info={start:'30',end_ms:3630000,width:1920,height:1080,rate:'30000/1001'};
assert.deepEqual(bounds(info),[30000,3630000]);
let plan={tracking:[createRegion('tracking','t0',30000,90000,info)],stabilization:[],selected_ids:[],selection:[30000,30000]};
plan=changeRegion(plan,'t0',{anchor:'mouth'},info);assert.equal(plan.tracking[0].anchor,'mouth');
plan=changeRegion(plan,'t0',{additional_anchors:['left_hand','right_hand','mouth','left_hand']},info);
assert.deepEqual(plan.tracking[0].additional_anchors,['left_hand','right_hand']);
plan=changeRegion(plan,'t0',{locked:true},info);
assert.throws(()=>changeRegion(plan,'t0',{start_ms:40000},info),/locked/);
assert.throws(()=>splitRegion(plan,'t0',60000,'t1',info),/Unlock/);
plan=changeRegion(plan,'t0',{locked:false},info);
plan=splitRegion(plan,'t0',60000,'t1',info);
assert.deepEqual(plan.tracking.map(r=>[r.start_ms,r.end_ms]),[[30000,60000],[60000,90000]]);
assert.equal(plan.tracking[1].anchor,'mouth');
assert.deepEqual(plan.tracking[1].additional_anchors,['left_hand','right_hand']);
assert.throws(()=>validateInterval(plan,'tracking','third',55000,65000,info),/overlaps/);
const stable=createRegion('stabilization','s0',30000,90000,info);stable.reference.points=[[10,10],[20,20],[30,30]];stable.reference.sections=[{id:'manual',keys:[]}];
plan.stabilization=[stable];
validateReference(stable);
assert.throws(()=>validateReference({...stable,reference:{...stable.reference,points:[[1,1]]}}),/three/);
const moved=changeRegion(plan,'s0',{start_ms:40000},info);assert.deepEqual(moved.stabilization[0].reference.points,[]);assert.deepEqual(moved.stabilization[0].reference.sections,[]);
assert.equal(plan.stabilization[0].reference.points.length,3,'edits must not mutate the saved plan');
const split=splitRegion(plan,'s0',60000,'s1',info);assert.equal(split.stabilization[0].reference.points.length,3);assert.deepEqual(split.stabilization[1].reference.points,[]);
assert.deepEqual(selectionRange({...plan,selection:[70000,50000]},info),[50000,70000]);
const rows=regionRows([{id:'a',start_ms:0,end_ms:10},{id:'b',start_ms:5,end_ms:15},{id:'c',start_ms:10,end_ms:20}]);assert.equal(rows.count,2);assert.equal(rows.positions.get('a'),rows.positions.get('c'));
const full=timelineView(info.end_ms,{span_ms:info.end_ms,start_ms:0}),zoom=zoomView(info.end_ms,full,30000,1800000),pan=panView(info.end_ms,zoom,3600000);
assert.equal(zoom.span_ms,30000);assert.equal(pan.start_ms,3600000);assert.ok(rulerTicks(0,info.end_ms,1200,info.end_ms).length<30);
console.log('Processing timeline: original-clock trims, locks, nonoverlap, independent lanes, reference resets, splits, and hour navigation passed');

const fullPlan={tracking:[createRegion('tracking','full',30000,120000,info)],stabilization:[],selection:[45000,75000],selected_ids:['full']};let id=0;const isolated=isolateSelection(fullPlan,'full',()=>`piece${id++}`,info);assert.deepEqual(isolated.tracking.map(r=>[r.start_ms,r.end_ms]),[[30000,45000],[45000,75000],[75000,120000]]);assert.equal(isolated.selected_ids[0],isolated.tracking[1].id);assert.deepEqual(isolated.selection,[45000,75000]);assert.equal(fullPlan.tracking.length,1);

// Cut-selected ranges become actual regions without losing anchors or locks.
const fromCuts=regionFromSelection(fullPlan,'tracking',()=>`cut${id++}`,info);
assert.deepEqual(fromCuts.tracking.map(r=>[r.start_ms,r.end_ms]),[[30000,45000],[45000,75000],[75000,120000]]);
assert.equal(fullPlan.tracking.length,1,'making a cut region does not mutate its input');
const lockedFull=structuredClone(fullPlan);lockedFull.tracking[0].locked=true;
assert.throws(()=>regionFromSelection(lockedFull,'tracking',()=>`cut${id++}`,info),/Unlock/);
lockedFull.selection=[30000,120000];assert.equal(regionFromSelection(lockedFull,'tracking',()=>'',info).selected_ids[0],'full');
assert.throws(()=>regionFromSelection({...fromCuts,selection:[40000,100000]},'tracking',()=>'',info),/crosses existing regions/);
const added=regionFromSelection(fullPlan,'stabilization',()=>`stable${id++}`,info);
assert.deepEqual(added.stabilization.map(r=>[r.start_ms,r.end_ms]),[[45000,75000]]);
assert.deepEqual(added.stabilization[0].reference.points,[]);
assert.deepEqual(added.tracking,fullPlan.tracking);

// Split on presentation timestamps, including VFR and a trim between frames.
const {frameClock}=await import('../assets/frame-clock.mjs');
const {splitAtTime}=await import('../assets/processing-timeline-edit.mjs');
const clock=frameClock({first_frame:17,end_frame:25,times_ms:[30000,30035,30090,30130,30210,30255,30330,30400],end_ms:30490});
const shortInfo={...info,end_ms:30490};
const a=[[10,10],[20,20],[30,30]],b=a.map(p=>p.map(v=>v+1)),c=a.map(p=>p.map(v=>v+2));
const marked=createRegion('stabilization','marked',30010,30490,shortInfo);
marked.reference={crop_xywh:[0,0,100,100],tracking_mode:'offline',points:a,keyframes:[{frame:0,points:a},{frame:3,points:b},{frame:5,points:c,unconfirmed:[1]}],
    point_mask:{frame:1,strokes:[{radius:8,erase:false,points:[[20,20]]}],model:'sam2.1_base_plus',spacing:7,limit:100},
    sections:[{id:'correction',keys:[{at_ms:0,xy:[0,0]},{at_ms:365,xy:[365,730]}]}]};
const markedPlan={tracking:[createRegion('tracking','poses',30010,30490,shortInfo)],stabilization:[marked],selection:[30010,30490],selected_ids:['marked']};
const untouched=structuredClone(markedPlan);
const pieces=splitRegion(markedPlan,'marked',30210,'right',shortInfo,clock),[left,right]=pieces.stabilization;
assert.equal(left.id,'marked');assert.equal(left.end_ms,right.start_ms);assert.equal(right.start_ms,30210);
assert.deepEqual(left.reference.keyframes,[{frame:0,points:a}]);
assert.deepEqual(right.reference.keyframes,[{frame:0,points:b},{frame:2,points:c,unconfirmed:[1]}]);
assert.deepEqual(right.reference.points,b);assert.deepEqual(left.reference.point_mask,marked.reference.point_mask);assert.equal(right.reference.point_mask,undefined);
assert.deepEqual(left.reference.sections[0].keys,[{at_ms:0,xy:[0,0]},{at_ms:95,xy:[95,190]}]);
assert.deepEqual(right.reference.sections[0].keys,[{at_ms:0,xy:[175,350]},{at_ms:190,xy:[365,730]}]);
assert.equal(right.reference.tracking_mode,'offline');
right.reference.crop_xywh[0]=9;right.reference.keyframes[0].points[0][0]=99;
assert.equal(left.reference.crop_xywh[0],0);assert.deepEqual(markedPlan,untouched,'split and subsequent right-side edits preserve the original/left data');
const seedAtCut=structuredClone(markedPlan);seedAtCut.stabilization[0].reference.point_mask.frame=3;
const maskPieces=splitRegion(seedAtCut,'marked',30210,'right',shortInfo,clock).stabilization;
assert.equal(maskPieces[0].reference.point_mask,undefined);assert.equal(maskPieces[1].reference.point_mask.frame,0,'mask on boundary belongs only to the right side');
const noRightKeys=structuredClone(markedPlan);noRightKeys.stabilization[0].reference.keyframes=[{frame:0,points:a}];
assert.deepEqual(splitRegion(noRightKeys,'marked',30210,'right',shortInfo,clock).stabilization[1].reference.points,[],'never copy point coordinates to an unmarked frame');
let serial=0;const both=splitAtTime(markedPlan,['tracking','stabilization'],30210,()=>`both${serial++}`,shortInfo,clock);
assert.deepEqual(both.tracking.map(r=>[r.start_ms,r.end_ms]),[[30010,30210],[30210,30490]]);
assert.deepEqual(both.stabilization.map(r=>[r.start_ms,r.end_ms]),[[30010,30210],[30210,30490]]);
assert.equal(both.selected_ids.length,2);
const protectedPlan=structuredClone(markedPlan);protectedPlan.stabilization[0].locked=true;
assert.throws(()=>splitAtTime(protectedPlan,['tracking','stabilization'],30210,()=>`locked${serial++}`,shortInfo,clock),/Unlock/);
assert.equal(protectedPlan.tracking.length,1,'both lanes split atomically, including lock rejection');
assert.throws(()=>splitAtTime(markedPlan,['tracking'],30000,()=>'',shortInfo,clock),/No region/);
assert.throws(()=>splitRegion(markedPlan,'marked',NaN,'invalid',shortInfo,clock),/inside/);
const isolatedReference=isolateSelection({...markedPlan,selection:[30130,30255]},'marked',()=>`isolate${serial++}`,shortInfo,clock);
assert.deepEqual(isolatedReference.stabilization.map(r=>r.reference.keyframes.filter(k=>k.points.length).map(k=>clock.ceil(r.start_ms)+k.frame)),[[18],[21],[23]]);
assert.equal(isolatedReference.stabilization[0].reference.point_mask.frame,1);
assert.equal(isolatedReference.stabilization[1].reference.point_mask,undefined);
console.log('Independent splits: exact VFR boundaries, retained mask/keyframe ownership, correction clipping, right-side rebasing, atomic lane splits, isolation and locks passed');
const meshPlan=structuredClone(markedPlan);
meshPlan.tracking[0].anchor='mask_anchor';meshPlan.tracking[0].mask_anchor={frame:3,strokes:[{erase:false,radius:8,points:[[20,20]]}]};
const meshId=meshPlan.tracking[0].id;
const meshSides=splitRegion(meshPlan,meshId,30210,'mask-right',shortInfo,clock).tracking;
assert.equal(meshSides[0].mask_anchor,undefined);
assert.equal(meshSides[1].mask_anchor.frame,0);
assert.deepEqual(meshSides[1].mask_anchor.strokes,meshPlan.tracking[0].mask_anchor.strokes);
assert.throws(()=>splitRegion(meshPlan,meshId,30210,'mask-right',shortInfo),/frame index/);
assert.equal(changeRegion(meshPlan,meshId,{end_ms:30210},shortInfo).tracking[0].mask_anchor,undefined);
assert.deepEqual(changeRegion(meshPlan,meshId,{name:'renamed'},shortInfo).tracking[0].mask_anchor,meshPlan.tracking[0].mask_anchor);
console.log('Painted anchors retain exact reference-frame ownership on splits and reset on bounds changes');
