import assert from "node:assert/strict";
import {correctedMotion,curveBuckets,referenceKeys,withReferenceKeys,addReferenceKey,putReferencePoint,removeReferencePoint,validateReferenceKeys} from "../assets/reference-edit.mjs";
const times=[0,20,70,100,160,200],shifts=times.map(()=>[0,0]);
const sections=[{keys:[{at_ms:20,xy:[12,20]},{at_ms:100,xy:[20,28]}]},{keys:[{at_ms:160,xy:[14,22]}]}];
const result=correctedMotion(times,shifts,[true,false,false,true,false,true],[10,20],sections);
assert.deepEqual(result.shifts,[[0,0],[2,0],[7,5],[10,8],[4,2],[0,0]]);
assert.deepEqual(result.quality,["tracked","manual","manual","manual","manual","tracked"]);
assert.deepEqual(shifts,times.map(()=>[0,0]));
assert.throws(()=>correctedMotion(times,shifts,times.map(()=>true),[0,0],[sections[0],sections[0]]),/overlap/);
const longTimes=Array.from({length:115201},(_,i)=>i*31.25),longShifts=longTimes.map(()=>[0,0]),quality=longTimes.map(()=>"tracked");
longShifts[60001]=[99,-70];quality[60001]="held";
const full=curveBuckets(longTimes,longShifts,quality,0,3600000,900);
assert.equal(full.length,900);assert.equal(Math.max(...full.map(b=>b.max[0])),99);assert.ok(full.some(b=>b.quality===2));
const zoomed=curveBuckets(longTimes,longShifts,quality,60000,70000,900);
assert.equal(Math.max(...zoomed.filter(b=>Number.isFinite(b.max[0])).map(b=>b.max[0])),0);
assert.ok(zoomed.every(b=>b.quality===0));
console.log("Reference preview parity, bounded corrections, overlap rejection, and hour-long timeline extrema passed.");
let reference={crop_xywh:[0,0,128,128],points:[],sections:[]};
reference=addReferenceKey(reference,12);
assert.deepEqual(referenceKeys(reference),[{frame:12,points:[]}]);
for(const [i,p]of [[20,20],[40,20],[30,40]].entries())reference=putReferencePoint(reference,12,i,p);
reference=addReferenceKey(reference,4);
assert.throws(()=>validateReferenceKeys(reference),/same numbered/);
for(const [i,p]of [[15,20],[35,20],[25,40]].entries())reference=putReferencePoint(reference,4,i,p);
validateReferenceKeys(reference,13);assert.throws(()=>validateReferenceKeys(reference,12),/inside/);
assert.deepEqual(reference.keyframes.map(k=>k.frame),[4,12]);assert.deepEqual(reference.points,reference.keyframes[0].points);
reference=putReferencePoint(reference,4,1,[36,21]);assert.deepEqual(reference.keyframes[1].points[1],[40,20]);
assert.throws(()=>putReferencePoint(reference,4,3,[50,20]),/same numbered/);
reference=removeReferencePoint(reference,1);assert.deepEqual(reference.keyframes.map(k=>k.points.length),[2,2]);
assert.deepEqual(reference.keyframes[1].points[1],[30,40]);
assert.deepEqual(withReferenceKeys(reference,[]).points,[]);
console.log('Reference keyframes: any seed frame, matching identities, corrections, incomplete drafts and deletion passed.');
